### ISSUE TITLE
ValueError: invalid literal for int() with base 10: 'N8'

### ISSUE THREAD

**Issue by hackerzone85** [tubiana/propka2graph#1]
``` javascript
blab@blab:~/Downloads/ProPka/propka2graph$ python propka2graph.py -f 4DFR.pka -c A -b GRAPH
***********************************************
**********  PROPKA 2 GRAPH V1.0  **************
***********************************************

Traceback (most recent call last):
  File "propka2graph.py", line 207, in <module>
    pkaDict=FileToDict(filePath)
  File "propka2graph.py", line 52, in FileToDict
    number=int(line[6:10])
ValueError: invalid literal for int() with base 10: 'N8'
```

**Comment by tubiana** [comment]
Hi, 

I just tried on a propka file (obtained from PDB2PQR program or from the webserver PDB2PQR (http://nbcr-222.ucsd.edu/pdb2pqr_2.0.0/) )/ And it works fine, I managed to get my graph.

Basicaly the error that you get is a malformed file (he tried to convert "N8" in integer). How did you got you 4DFR.pka?

Also -b argument is invalid, it has to be Y or N.

**Comment by hackerzone85** [comment]
by using https://github.com/jensengroup/propka-3.1 tool to get pka of 4DFR

On Mon, Oct 26, 2015 at 5:26 PM, Thibault Tubiana notifications@github.com
wrote:

> Hi,
> 
> I just tried on a propka file (obtained from PDB2PQR program or from the
> webserver PDB2PQR (http://nbcr-222.ucsd.edu/pdb2pqr_2.0.0/) )/ And it
> works fine, I managed to get my graph.
> 
> Basicaly the error that you get is a malformed file (he tried to convert
> "N8" in integer). How did you got you 4DFR.pka?
> 
> Also -b argument is invalid, it has to be Y or N.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/tubiana/propka2graph/issues/1#issuecomment-151111136.

## 

Mahendra Gaur (M.Tech Bioinformatics, GBU, NOIDA)
Project Assistant
Biomics & Biodiversity Lab
Centre of Biotechnology
Siksha ‘O’ Anusandhan University
Kalinga Nagar, Ghatikia
Bhubaneswar-751003
E-Mail.-mahendra.gbu@gmail.com (primary)
           mahi61285@gmail.com
Mob. - -+91-9694157484 (Kota)
          -+91-9583630937 (BBSR)
          -+91-7683986167 (BBSR)

**Comment by tubiana** [comment]
Thanks, 
4DFR contains a non standard amino acids (MTX) and the resinue nomber was not good on the PKA file (N8, it was the atom name)

I just add a try/except to avoid crash with this kind of molecule, so you will not have a graphic on theses kind of molecule (only for standard amino acid).

If I have time i will try to support them in the future.

I tried on 4DFR downloaded from PDB and it worked, does it works for you too ?

**Comment by tubiana** [comment]
Hi again,

I pushed a new update, now you will have graph of all kind of amino acid/molecule such as MTX present in 4DFR.

Thibault.

**Comment by hackerzone85** [comment]
_"Wish you all and your Family a Very Happy, Healthy and Prosperous New
Year 2016."_

Thanks & Regards

## 

Mahendra Gaur (M.Tech Bioinformatics, GBU, NOIDA)
Project Assistant
Biomics & Biodiversity Lab
Centre of Biotechnology
Siksha ‘O’ Anusandhan University
Kalinga Nagar, Ghatikia
Bhubaneswar-751003
E-Mail.-mahendra.gbu@gmail.com (primary)
           mahi61285@gmail.com
Mob. :- +91-9583630937 (BBSR)
           +91-9694157484 (Kota)
           +91-7683986167 (BBSR)

_RG Profile:_ https://www.researchgate.net/profile/Mahendra_Gaur4

**Comment by tubiana** [comment]
Thank you, you too :)

Thibault.
